/**
 * Accounts we watch for breaking football news.
 * Add/remove handles freely (without @).
 */
export const BREAKERS = [
  { handle: "FabrizioRomano", label: "Fabrizio Romano", weight: 10 },
  { handle: "David_Ornstein", label: "David Ornstein", weight: 10 },
  { handle: "BenJacobs_", label: "Ben Jacobs", weight: 8 },
  { handle: "SkySportsNews", label: "Sky Sports News", weight: 7 },
  { handle: "JacobSteinberg", label: "Jacob Steinberg", weight: 7 },
  { handle: "alex_crook", label: "Alex Crook", weight: 6 },
  { handle: "SimonStoneNews", label: "Simon Stone", weight: 7 },
  { handle: "JamesBenge", label: "James Benge", weight: 6 },
  { handle: "DuncanCastles", label: "Duncan Castles", weight: 6 },
  { handle: "IndyFootball", label: "The Independent Football", weight: 5 },
  { handle: "Plettigoal", label: "Plettigoal", weight: 7 },

  // Club correspondents — 2026-27 Premier League, one per club (David_Ornstein
  // above already covers Arsenal). Mostly Athletic beat writers; a few strong
  // local-paper reporters where that's the best-connected voice on the club.
  { handle: "greggevans40", label: "Gregg Evans (Aston Villa)", weight: 8 },
  { handle: "AlexSmithEcho", label: "Alexander Smith (Bournemouth)", weight: 6 },
  { handle: "AndyNaylorBHAFC", label: "Andy Naylor (Brighton)", weight: 8 },
  { handle: "SJohnsonSport", label: "Simon Johnson (Chelsea)", weight: 8 },
  { handle: "AndyTurnerccfc", label: "Andy Turner (Coventry City)", weight: 6 },
  { handle: "MattWoosie", label: "Matt Woosnam (Crystal Palace)", weight: 8 },
  { handle: "Paddy_Boyland", label: "Patrick Boyland (Everton)", weight: 8 },
  { handle: "peterrutzler", label: "Peter Rutzler (Fulham)", weight: 8 },
  { handle: "PJBuckingham", label: "Philip Buckingham (Hull City)", weight: 7 },
  { handle: "Stuart_Watson", label: "Stuart Watson (Ipswich Town)", weight: 7 },
  { handle: "BerenCross", label: "Beren Cross (Leeds United)", weight: 8 },
  { handle: "JamesPearceLFC", label: "James Pearce (Liverpool)", weight: 8 },
  { handle: "SamLee", label: "Sam Lee (Manchester City)", weight: 8 },
  { handle: "lauriewhitwell", label: "Laurie Whitwell (Manchester United)", weight: 8 },
  { handle: "ChrisDHWaugh", label: "Chris Waugh (Newcastle United)", weight: 8 },
  { handle: "nottmtails", label: "Paul Taylor (Nottingham Forest)", weight: 7 },
  { handle: "RichMennear", label: "Richard Mennear (Sunderland)", weight: 6 },
  { handle: "AlasdairGold", label: "Alasdair Gold (Tottenham)", weight: 8 },
  // Brentford: no single dominant beat-insider identified — worth a manual
  // pick if you follow one closely; leaving out rather than guessing.
];

/** Free RSS feeds used when X read access is not configured yet. */
export const RSS_FEEDS = [
  {
    name: "BBC Sport Football",
    url: "https://feeds.bbci.co.uk/sport/football/rss.xml",
    handle: "BBCSport",
  },
  {
    name: "Guardian Football",
    url: "https://www.theguardian.com/football/rss",
    handle: "guardian_sport",
  },
  {
    name: "ESPN FC",
    url: "https://www.espn.com/espn/rss/soccer/news",
    handle: "ESPNFC",
  },
];

/**
 * Hard transfer / breaking-news phrases.
 * Avoid lone words like "deal" / "transfer" that match opinion chatter.
 */
export const HARD_NEWS_PHRASES = [
  "here we go",
  "exclusive",
  "excl:",
  "exc:",
  "medical",
  "personal terms",
  "done deal",
  "verbal agreement",
  "reach agreement",
  "reached an agreement",
  "agreement in principle",
  "agreement with",
  "official bid",
  "first bid",
  "have bid",
  "has bid",
  "submitted a bid",
  "rejected a",
  "turned down",
  "offer rejected",
  "rejected an offer",
  "rejected a formal",
  "set to join",
  "set to sign",
  "close to joining",
  "close to signing",
  "on the verge",
  "completed the signing",
  "have signed",
  "has signed",
  "have completed",
  "loan deal",
  "on loan",
  "season-long loan",
  "sell-on",
  "add-ons",
  "add ons",
  "release clause",
  "transfer fee",
  "transfer agreed",
  "transfer complete",
  "joining from",
  "joins from",
  "to sign",
  "to join",
  "move to",
  "move from",
  "deal worth",
  "fee of",
  "fee is",
  "combined fee",
  "negotiations underway",
  "talks underway",
  "advancing in talks",
  "announcement is imminent",
  "imminent",
];

/**
 * Soft rumour / interest language — only posted when a Premier League club is named.
 */
export const RUMOUR_PHRASES = [
  "rumour",
  "rumor",
  "rumours",
  "rumors",
  "rumoured",
  "rumored",
  "interested in",
  "have interest",
  "has interest",
  "shown interest",
  "showing interest",
  "keen on",
  "monitoring",
  "tracking",
  "targeting",
  "eyeing",
  "linked with",
  "linked to",
  "among clubs interested",
  "want to sign",
  "wants to sign",
  "looking to sign",
  "making enquiries",
  "made enquiries",
  "enquired about",
  "inquired about",
  "held talks",
  "exploratory talks",
  "gauging interest",
  "open to offers",
  "available for transfer",
];

/** Drop studio chat, polls, hot takes, engagement bait. */
export const NOISE_PATTERNS = [
  /leave your questions/i,
  /in the studio/i,
  /football club is back/i,
  /undervalued/i,
  /\bhot take\b/i,
  /\bmy opinion\b/i,
  /\bi think\b/i,
  /\bdo (you|arsenal|city|united|liverpool|chelsea|spurs)\b.*\?/i,
  /\bshould (arsenal|city|united|liverpool|chelsea)\b/i,
  /\bbest ever\b/i,
  /\bgreat games\b/i,
  /\bshocking final\b/i,
  /\bvote now\b/i,
  /\bpoll\b/i,
  /\bgiveaway\b/i,
  /\bfollow (me|us) for\b/i,
  /\bsubscribe\b/i,
  /\blive now\b/i,
  /\bjoin us (at|on|from)\b/i,
  /\bwatch live\b/i,
];

/**
 * Premier League clubs + common tipster shorthand / hashtags.
 * Matched case-insensitively as whole phrases where needed.
 */
export const PREMIER_LEAGUE_TERMS = [
  "arsenal",
  "#afc",
  "gunners",
  "chelsea",
  "#cfc",
  "tottenham",
  "spurs",
  "#thfc",
  "newcastle",
  "#nufc",
  "magpies",
  "aston villa",
  "avfc",
  "#avfc",
  "west ham",
  "#whu",
  "hammers",
  "brighton",
  "#bhafc",
  "seagulls",
  "fulham",
  "#fulhamfc",
  "#ffc",
  "brentford",
  "crystal palace",
  "#cpfc",
  "wolves",
  "wolverhampton",
  "#wwfc",
  "everton",
  "#efc",
  "toffees",
  "nottingham forest",
  "nottm forest",
  "#nffc",
  "bournemouth",
  "#afcb",
  "cherries",
  "leeds",
  "leeds united",
  "#lufc",
  "sunderland",
  "#safc",
  "burnley",
  "clarets",
  "ipswich",
  "leicester",
  "southampton",
  "saints",
  "liverpool",
  "#lfc",
  "manchester united",
  "man united",
  "man utd",
  "#mufc",
  "manchester city",
  "man city",
  "#mcfc",
  "premier league",
];

/**
 * High-profile European clubs — keep big continental deals even if not PL.
 */
export const ELITE_EUROPE_TERMS = [
  "real madrid",
  "barcelona",
  "barça",
  "barca",
  "atletico madrid",
  "atlético madrid",
  "atleti",
  "bayern",
  "bayern munich",
  "bayern münchen",
  "borussia dortmund",
  "dortmund",
  "bvb",
  "psg",
  "paris saint-germain",
  "paris saint germain",
  "juventus",
  "juve",
  "inter milan",
  "inter",
  "ac milan",
  "milan",
  "napoli",
  "as roma",
  "roma",
  "lazio",
  "atalanta",
  "ajax",
  "benfica",
  "porto",
  "sporting cp",
  "rb leipzig",
  "leipzig",
  "bayer leverkusen",
  "leverkusen",
  "marseille",
  "olympique marseille",
  "lyon",
  "monaco",
  "sevilla",
  "villarreal",
  "valencia",
  "galatasaray",
  "fenerbahce",
  "fenerbahçe",
  "besiktas",
  "beşiktaş",
  "celtic",
  "rangers",
  "olympiacos",
  "olympiakós",
];

/** Minimum fee (millions) for a non-PL elite-Europe tip to count as “high profile”. */
export const HIGH_PROFILE_FEE_M = 15;